name: ci-poc-golang-workflow
on: [push]
jobs:
  check-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - run: go test
      - run: go run math.go